-- ═══════════════════════════════════════════════════════════════════
-- OpenClaw Trading System — PostgreSQL Database Schema
-- ═══════════════════════════════════════════════════════════════════

-- Create database and user (run as superuser)
-- CREATE DATABASE trading;
-- CREATE USER trader WITH PASSWORD 'change_me_in_production';
-- GRANT ALL PRIVILEGES ON DATABASE trading TO trader;

-- ═══════════════════════════════════════════════════════════════════
-- CORE TABLES
-- ═══════════════════════════════════════════════════════════════════

-- Signals generated by the brain
CREATE TABLE IF NOT EXISTS signals (
    id                  SERIAL PRIMARY KEY,
    signal_id           VARCHAR(60) UNIQUE NOT NULL,
    timestamp_utc       TIMESTAMP WITH TIME ZONE NOT NULL,
    expires_utc         TIMESTAMP WITH TIME ZONE NOT NULL,
    asset               VARCHAR(10) NOT NULL,
    action              VARCHAR(20) NOT NULL,
    direction           VARCHAR(5) NOT NULL,
    entry_price_ref     DECIMAL(14,5) NOT NULL,
    stop_loss           DECIMAL(14,5) NOT NULL,
    take_profit_1       DECIMAL(14,5),
    take_profit_2       DECIMAL(14,5),
    take_profit_3       DECIMAL(14,5),
    position_size_lots  DECIMAL(8,4) NOT NULL,
    risk_percent        DECIMAL(6,4) NOT NULL,
    risk_usd            DECIMAL(12,2) NOT NULL,
    sl_distance_usd     DECIMAL(12,2) NOT NULL,
    rr_ratio            DECIMAL(5,2) NOT NULL,

    -- Context at signal generation
    regime              VARCHAR(25),
    d1_bias             VARCHAR(10),
    h4_bias             VARCHAR(10),
    h1_trend            VARCHAR(10),
    m15_trigger         VARCHAR(40),
    atr_h1              DECIMAL(14,5),
    adx_h1              DECIMAL(5,1),
    vol_ratio           DECIMAL(5,2),
    bb_width_percentile INTEGER,
    mtf_bias_score      DECIMAL(5,2),
    spread_at_signal    DECIMAL(8,2),
    consecutive_losses  INTEGER,
    daily_dd_pct        DECIMAL(5,3),
    monthly_dd_pct      DECIMAL(5,3),
    risk_state          VARCHAR(15),
    allocation_weight   DECIMAL(5,4),
    btc_eth_correlation DECIMAL(5,3),

    -- Outcome
    status              VARCHAR(25) DEFAULT 'PENDING',
    -- PENDING, FILLED, REJECTED_VALIDATOR, REJECTED_BROKER, EXPIRED, ERROR

    created_at          TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE INDEX idx_signals_asset ON signals(asset);
CREATE INDEX idx_signals_timestamp ON signals(timestamp_utc);
CREATE INDEX idx_signals_status ON signals(status);


-- ═══════════════════════════════════════════════════════════════════
-- TRADE JOURNAL (closed trades — the most important table)
-- ═══════════════════════════════════════════════════════════════════

CREATE TABLE IF NOT EXISTS trade_journal (
    id                  SERIAL PRIMARY KEY,
    signal_id           VARCHAR(60) REFERENCES signals(signal_id),
    ticket              BIGINT,
    asset               VARCHAR(10) NOT NULL,
    direction           VARCHAR(5) NOT NULL,

    -- Timing
    entry_time_utc      TIMESTAMP WITH TIME ZONE NOT NULL,
    exit_time_utc       TIMESTAMP WITH TIME ZONE,
    hold_duration_min   INTEGER,

    -- Prices
    entry_price         DECIMAL(14,5) NOT NULL,
    exit_price          DECIMAL(14,5),
    stop_loss_initial   DECIMAL(14,5) NOT NULL,
    stop_loss_final     DECIMAL(14,5),
    take_profit_target  DECIMAL(14,5),

    -- Size
    lots                DECIMAL(8,4) NOT NULL,
    risk_pct_planned    DECIMAL(6,4) NOT NULL,
    risk_usd_planned    DECIMAL(12,2),

    -- P&L
    pnl_gross           DECIMAL(12,2),
    pnl_net             DECIMAL(12,2),
    commission          DECIMAL(8,2) DEFAULT 0,
    swap                DECIMAL(8,2) DEFAULT 0,
    slippage_entry      DECIMAL(8,2) DEFAULT 0,
    slippage_exit       DECIMAL(8,2) DEFAULT 0,

    -- R:R
    rr_planned          DECIMAL(5,2),
    rr_achieved         DECIMAL(5,2),

    -- Exit info
    exit_reason         VARCHAR(30),
    -- TP1, TP2, TP3, SL, TRAILING, MANUAL, KILL_SWITCH, TIME_EXIT
    partial_closes      JSONB,

    -- Context at entry (denormalized for fast queries)
    regime_at_entry     VARCHAR(25),
    adx_at_entry        DECIMAL(5,1),
    atr_at_entry        DECIMAL(14,5),
    vol_ratio_at_entry  DECIMAL(5,2),
    bb_width_pctl       INTEGER,
    mtf_bias_score      DECIMAL(5,2),
    alignment_quality   VARCHAR(10),
    d1_bias             VARCHAR(10),
    h4_bias             VARCHAR(10),
    h1_trend            VARCHAR(10),
    m15_trigger_type    VARCHAR(40),
    spread_at_entry     DECIMAL(8,2),
    allocation_weight   DECIMAL(5,4),
    risk_state          VARCHAR(15),
    consecutive_losses  INTEGER,
    daily_dd_at_entry   DECIMAL(5,3),
    monthly_dd_at_entry DECIMAL(5,3),
    btc_eth_corr        DECIMAL(5,3),

    -- Post-trade analysis (computed after close)
    max_favorable_excursion     DECIMAL(12,2),  -- MFE in USD
    max_adverse_excursion       DECIMAL(12,2),  -- MAE in USD
    time_to_max_profit_min      INTEGER,
    was_optimal_exit            BOOLEAN,

    created_at          TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE INDEX idx_trades_asset ON trade_journal(asset);
CREATE INDEX idx_trades_entry_time ON trade_journal(entry_time_utc);
CREATE INDEX idx_trades_exit_time ON trade_journal(exit_time_utc);
CREATE INDEX idx_trades_direction ON trade_journal(direction);
CREATE INDEX idx_trades_exit_reason ON trade_journal(exit_reason);
CREATE INDEX idx_trades_regime ON trade_journal(regime_at_entry);
CREATE INDEX idx_trades_signal_id ON trade_journal(signal_id);


-- ═══════════════════════════════════════════════════════════════════
-- EXECUTION CONFIRMATIONS
-- ═══════════════════════════════════════════════════════════════════

CREATE TABLE IF NOT EXISTS execution_confirmations (
    id                  SERIAL PRIMARY KEY,
    confirmation_id     VARCHAR(60) UNIQUE NOT NULL,
    signal_id           VARCHAR(60) REFERENCES signals(signal_id),
    timestamp_utc       TIMESTAMP WITH TIME ZONE NOT NULL,
    status              VARCHAR(25) NOT NULL,
    ticket              BIGINT,
    asset               VARCHAR(10),
    fill_price          DECIMAL(14,5),
    slippage_usd        DECIMAL(8,2),
    slippage_points     DECIMAL(8,2),
    actual_lots         DECIMAL(8,4),
    execution_time_ms   DECIMAL(8,1),
    commission          DECIMAL(8,2),
    spread_at_fill      DECIMAL(8,2),
    rejection_reason    VARCHAR(40),
    rejection_detail    TEXT,
    broker_comment      TEXT,
    account_equity      DECIMAL(14,2),
    account_balance     DECIMAL(14,2),

    created_at          TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE INDEX idx_confirmations_signal ON execution_confirmations(signal_id);
CREATE INDEX idx_confirmations_status ON execution_confirmations(status);


-- ═══════════════════════════════════════════════════════════════════
-- EQUITY SNAPSHOTS (every 5 minutes)
-- ═══════════════════════════════════════════════════════════════════

CREATE TABLE IF NOT EXISTS equity_snapshots (
    id                  SERIAL PRIMARY KEY,
    timestamp_utc       TIMESTAMP WITH TIME ZONE NOT NULL,
    balance             DECIMAL(14,2) NOT NULL,
    equity              DECIMAL(14,2) NOT NULL,
    floating_pnl        DECIMAL(12,2),
    margin_used         DECIMAL(12,2),
    margin_free         DECIMAL(12,2),
    margin_level_pct    DECIMAL(10,2),
    open_positions      INTEGER,
    daily_dd_pct        DECIMAL(5,3),
    monthly_dd_pct      DECIMAL(5,3),
    risk_state          VARCHAR(15),

    created_at          TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE INDEX idx_equity_timestamp ON equity_snapshots(timestamp_utc);

-- Partition by month for performance (large table)
-- In production, use PostgreSQL partitioning:
-- CREATE TABLE equity_snapshots (...) PARTITION BY RANGE (timestamp_utc);


-- ═══════════════════════════════════════════════════════════════════
-- DAILY EQUITY BASELINES
-- ═══════════════════════════════════════════════════════════════════

CREATE TABLE IF NOT EXISTS daily_equity_snapshot (
    id                  SERIAL PRIMARY KEY,
    date                DATE UNIQUE NOT NULL,
    equity              DECIMAL(14,2) NOT NULL,
    created_at          TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS monthly_equity_snapshot (
    id                  SERIAL PRIMARY KEY,
    month_start         DATE UNIQUE NOT NULL,
    equity              DECIMAL(14,2) NOT NULL,
    created_at          TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);


-- ═══════════════════════════════════════════════════════════════════
-- REGIME CLASSIFICATION LOG
-- ═══════════════════════════════════════════════════════════════════

CREATE TABLE IF NOT EXISTS regime_log (
    id                  SERIAL PRIMARY KEY,
    timestamp_utc       TIMESTAMP WITH TIME ZONE NOT NULL,
    asset               VARCHAR(10) NOT NULL,
    timeframe           VARCHAR(5) NOT NULL,
    regime              VARCHAR(25) NOT NULL,
    adx                 DECIMAL(5,1),
    atr                 DECIMAL(14,5),
    vol_ratio           DECIMAL(5,2),
    bb_width_pctl       INTEGER,
    bias                DECIMAL(5,2),
    trend_strength      VARCHAR(15),

    created_at          TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE INDEX idx_regime_asset_time ON regime_log(asset, timestamp_utc);
CREATE INDEX idx_regime_regime ON regime_log(regime);


-- ═══════════════════════════════════════════════════════════════════
-- ALLOCATION HISTORY
-- ═══════════════════════════════════════════════════════════════════

CREATE TABLE IF NOT EXISTS allocation_history (
    id                  SERIAL PRIMARY KEY,
    timestamp_utc       TIMESTAMP WITH TIME ZONE NOT NULL,
    weights             JSONB NOT NULL,
    -- {"BTCUSD": 0.42, "ETHUSD": 0.28, "XAUUSD": 0.30}
    previous_weights    JSONB,
    scores              JSONB,
    -- {"BTCUSD": {"performance": 68, "regime": 72, "composite": 69.6}, ...}
    btc_eth_correlation DECIMAL(5,3),
    allocation_state    VARCHAR(25),
    reason              VARCHAR(100),

    created_at          TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE INDEX idx_alloc_timestamp ON allocation_history(timestamp_utc);


-- ═══════════════════════════════════════════════════════════════════
-- ASSET PERFORMANCE SNAPSHOTS (computed every 4 hours)
-- ═══════════════════════════════════════════════════════════════════

CREATE TABLE IF NOT EXISTS asset_performance_snapshot (
    id                  SERIAL PRIMARY KEY,
    timestamp_utc       TIMESTAMP WITH TIME ZONE NOT NULL,
    asset               VARCHAR(10) NOT NULL,
    period_days         INTEGER NOT NULL,
    trade_count         INTEGER,
    win_count           INTEGER,
    loss_count          INTEGER,
    win_rate            DECIMAL(5,4),
    avg_win_usd         DECIMAL(12,2),
    avg_loss_usd        DECIMAL(12,2),
    avg_rr_achieved     DECIMAL(5,2),
    expectancy_usd      DECIMAL(12,2),
    profit_factor       DECIMAL(6,2),
    sharpe_ratio        DECIMAL(6,3),
    sortino_ratio       DECIMAL(6,3),
    max_drawdown_pct    DECIMAL(5,2),
    max_consec_wins     INTEGER,
    max_consec_losses   INTEGER,
    total_pnl_usd       DECIMAL(12,2),
    total_commission     DECIMAL(10,2),
    total_swap           DECIMAL(10,2),
    avg_hold_duration_min INTEGER,
    avg_slippage_usd     DECIMAL(8,2),
    allocation_weight    DECIMAL(5,4),
    regime_distribution  JSONB,

    created_at          TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE INDEX idx_perf_asset_time ON asset_performance_snapshot(asset, timestamp_utc);


-- ═══════════════════════════════════════════════════════════════════
-- DAILY REPORTS
-- ═══════════════════════════════════════════════════════════════════

CREATE TABLE IF NOT EXISTS daily_reports (
    id                  SERIAL PRIMARY KEY,
    date                DATE UNIQUE NOT NULL,
    report_data         JSONB NOT NULL,
    -- Full daily report as JSON (see 06-PERFORMANCE-TRACKING.md)
    starting_equity     DECIMAL(14,2),
    ending_equity       DECIMAL(14,2),
    net_pnl_usd         DECIMAL(12,2),
    net_pnl_pct         DECIMAL(6,3),
    max_drawdown_pct    DECIMAL(5,2),
    total_trades        INTEGER,
    win_rate            DECIMAL(5,4),

    created_at          TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);


-- ═══════════════════════════════════════════════════════════════════
-- MONTHLY REPORTS
-- ═══════════════════════════════════════════════════════════════════

CREATE TABLE IF NOT EXISTS monthly_reports (
    id                  SERIAL PRIMARY KEY,
    period              VARCHAR(7) UNIQUE NOT NULL,  -- 'YYYY-MM'
    report_data         JSONB NOT NULL,
    net_return_pct      DECIMAL(6,3),
    max_drawdown_pct    DECIMAL(5,2),
    sharpe_ratio        DECIMAL(6,3),
    total_trades        INTEGER,
    win_rate            DECIMAL(5,4),
    profit_factor       DECIMAL(6,2),

    created_at          TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);


-- ═══════════════════════════════════════════════════════════════════
-- KILL SWITCH LOG
-- ═══════════════════════════════════════════════════════════════════

CREATE TABLE IF NOT EXISTS kill_switch_log (
    id                  SERIAL PRIMARY KEY,
    timestamp_utc       TIMESTAMP WITH TIME ZONE NOT NULL,
    reason              TEXT NOT NULL,
    severity            VARCHAR(15) NOT NULL,
    source              VARCHAR(10) NOT NULL,  -- BRAIN or EA
    halt_type           VARCHAR(20),
    resume_after_utc    TIMESTAMP WITH TIME ZONE,
    equity_at_trigger   DECIMAL(14,2),
    daily_dd_pct        DECIMAL(5,3),
    monthly_dd_pct      DECIMAL(5,3),
    positions_closed    INTEGER,
    snapshot_data       JSONB,  -- Full system state at trigger time

    created_at          TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);


-- ═══════════════════════════════════════════════════════════════════
-- RISK EVENTS LOG
-- ═══════════════════════════════════════════════════════════════════

CREATE TABLE IF NOT EXISTS risk_events (
    id                  SERIAL PRIMARY KEY,
    timestamp_utc       TIMESTAMP WITH TIME ZONE NOT NULL,
    event_type          VARCHAR(40) NOT NULL,
    -- DAILY_DD_WARNING, DAILY_DD_SOFT_HALT, DAILY_DD_HARD_HALT,
    -- MONTHLY_DD_WARNING, CONSEC_LOSS_3, CONSEC_LOSS_5, CONSEC_LOSS_7,
    -- SPREAD_BLOWUP, HEARTBEAT_LOSS, FLASH_CRASH, RISK_STATE_CHANGE
    severity            VARCHAR(15) NOT NULL,
    asset               VARCHAR(10),
    detail              TEXT,
    metrics             JSONB,
    -- Relevant metrics at time of event

    created_at          TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE INDEX idx_risk_events_time ON risk_events(timestamp_utc);
CREATE INDEX idx_risk_events_type ON risk_events(event_type);


-- ═══════════════════════════════════════════════════════════════════
-- SELF-IMPROVEMENT LOG
-- ═══════════════════════════════════════════════════════════════════

CREATE TABLE IF NOT EXISTS self_improvement_log (
    id                  SERIAL PRIMARY KEY,
    timestamp_utc       TIMESTAMP WITH TIME ZONE NOT NULL,
    analysis_type       VARCHAR(30) NOT NULL,
    -- WEEKLY_REVIEW, TRIGGER_ANALYSIS, SL_ANALYSIS, TP_ANALYSIS,
    -- HOURLY_PERFORMANCE, REGIME_PERFORMANCE
    analysis_data       JSONB NOT NULL,
    recommendations     JSONB,
    actions_taken       JSONB,
    -- What parameters were actually changed

    created_at          TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);


-- ═══════════════════════════════════════════════════════════════════
-- CONFIGURATION HISTORY (audit trail)
-- ═══════════════════════════════════════════════════════════════════

CREATE TABLE IF NOT EXISTS config_history (
    id                  SERIAL PRIMARY KEY,
    timestamp_utc       TIMESTAMP WITH TIME ZONE NOT NULL,
    parameter           VARCHAR(50) NOT NULL,
    old_value           TEXT,
    new_value           TEXT NOT NULL,
    changed_by          VARCHAR(20) NOT NULL,  -- SYSTEM, MANUAL, SELF_IMPROVE
    reason              TEXT,

    created_at          TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);


-- ═══════════════════════════════════════════════════════════════════
-- MARKET DATA CACHE (for backtest validation)
-- ═══════════════════════════════════════════════════════════════════

CREATE TABLE IF NOT EXISTS market_data_cache (
    id                  BIGSERIAL PRIMARY KEY,
    asset               VARCHAR(10) NOT NULL,
    timeframe           VARCHAR(5) NOT NULL,
    bar_time            TIMESTAMP WITH TIME ZONE NOT NULL,
    open                DECIMAL(14,5) NOT NULL,
    high                DECIMAL(14,5) NOT NULL,
    low                 DECIMAL(14,5) NOT NULL,
    close               DECIMAL(14,5) NOT NULL,
    volume              BIGINT,
    spread              INTEGER,

    UNIQUE(asset, timeframe, bar_time)
);

CREATE INDEX idx_market_data ON market_data_cache(asset, timeframe, bar_time);


-- ═══════════════════════════════════════════════════════════════════
-- USEFUL VIEWS
-- ═══════════════════════════════════════════════════════════════════

-- Rolling 30-day performance by asset
CREATE OR REPLACE VIEW v_asset_performance_30d AS
SELECT
    asset,
    COUNT(*) AS trade_count,
    SUM(CASE WHEN pnl_net > 0 THEN 1 ELSE 0 END) AS wins,
    SUM(CASE WHEN pnl_net <= 0 THEN 1 ELSE 0 END) AS losses,
    ROUND(SUM(CASE WHEN pnl_net > 0 THEN 1 ELSE 0 END)::DECIMAL / COUNT(*), 4) AS win_rate,
    ROUND(AVG(CASE WHEN pnl_net > 0 THEN pnl_net END), 2) AS avg_win,
    ROUND(AVG(CASE WHEN pnl_net < 0 THEN ABS(pnl_net) END), 2) AS avg_loss,
    ROUND(SUM(pnl_net), 2) AS total_pnl,
    ROUND(AVG(rr_achieved), 2) AS avg_rr,
    ROUND(SUM(CASE WHEN pnl_net > 0 THEN pnl_net ELSE 0 END) /
          NULLIF(SUM(CASE WHEN pnl_net < 0 THEN ABS(pnl_net) ELSE 0 END), 0), 2)
        AS profit_factor,
    ROUND(AVG(hold_duration_min), 0) AS avg_hold_min,
    ROUND(AVG(slippage_entry + slippage_exit), 2) AS avg_slippage
FROM trade_journal
WHERE exit_time_utc >= NOW() - INTERVAL '30 days'
  AND exit_time_utc IS NOT NULL
GROUP BY asset;

-- Today's trades
CREATE OR REPLACE VIEW v_today_trades AS
SELECT *
FROM trade_journal
WHERE entry_time_utc >= CURRENT_DATE
ORDER BY entry_time_utc DESC;

-- Current drawdown status
CREATE OR REPLACE VIEW v_drawdown_status AS
SELECT
    d.date,
    d.equity AS daily_start,
    e.equity AS current_equity,
    ROUND((d.equity - e.equity) / d.equity * 100, 2) AS daily_dd_pct,
    m.equity AS monthly_start,
    ROUND((m.equity - e.equity) / m.equity * 100, 2) AS monthly_dd_pct
FROM daily_equity_snapshot d
CROSS JOIN (
    SELECT equity FROM equity_snapshots ORDER BY timestamp_utc DESC LIMIT 1
) e
LEFT JOIN monthly_equity_snapshot m ON m.month_start = DATE_TRUNC('month', CURRENT_DATE)
WHERE d.date = CURRENT_DATE;

-- Performance by regime
CREATE OR REPLACE VIEW v_regime_performance AS
SELECT
    regime_at_entry,
    COUNT(*) AS trades,
    ROUND(SUM(CASE WHEN pnl_net > 0 THEN 1 ELSE 0 END)::DECIMAL / COUNT(*), 4) AS win_rate,
    ROUND(SUM(pnl_net), 2) AS total_pnl,
    ROUND(AVG(rr_achieved), 2) AS avg_rr
FROM trade_journal
WHERE exit_time_utc IS NOT NULL
GROUP BY regime_at_entry
ORDER BY total_pnl DESC;

-- Performance by entry trigger
CREATE OR REPLACE VIEW v_trigger_performance AS
SELECT
    m15_trigger_type,
    COUNT(*) AS trades,
    ROUND(SUM(CASE WHEN pnl_net > 0 THEN 1 ELSE 0 END)::DECIMAL / COUNT(*), 4) AS win_rate,
    ROUND(SUM(pnl_net), 2) AS total_pnl,
    ROUND(AVG(rr_achieved), 2) AS avg_rr
FROM trade_journal
WHERE exit_time_utc IS NOT NULL
GROUP BY m15_trigger_type
ORDER BY total_pnl DESC;


-- ═══════════════════════════════════════════════════════════════════
-- DATA RETENTION POLICY
-- ═══════════════════════════════════════════════════════════════════

-- equity_snapshots:     Keep 1 year at 5-min resolution, then downsample to hourly
-- regime_log:           Keep 6 months
-- trade_journal:        Keep forever (core audit trail)
-- signals:              Keep 1 year
-- market_data_cache:    Keep 2 years (for backtesting)

-- Downsampling job (run monthly via cron):
-- INSERT INTO equity_snapshots_hourly
-- SELECT DATE_TRUNC('hour', timestamp_utc) AS timestamp_utc,
--        AVG(balance), AVG(equity), ...
-- FROM equity_snapshots
-- WHERE timestamp_utc < NOW() - INTERVAL '1 year'
-- GROUP BY DATE_TRUNC('hour', timestamp_utc);
--
-- DELETE FROM equity_snapshots WHERE timestamp_utc < NOW() - INTERVAL '1 year';
