-- ============================================================================
-- OpenClaw Trading System — PostgreSQL Database Schema
-- ============================================================================
-- This schema supports the full trading lifecycle: signals, trades, performance,
-- risk events, system health, and self-improvement audit trail.
-- ============================================================================

-- Enable extensions
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "timescaledb";  -- Optional: for time-series optimization

-- ============================================================================
-- 1. SIGNALS TABLE
-- Records every signal generated by OpenClaw, regardless of outcome.
-- ============================================================================
CREATE TABLE signals (
    id                  UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    signal_id           VARCHAR(100) UNIQUE NOT NULL,
    signal_type         VARCHAR(20) NOT NULL,  -- ENTRY, EXIT, MODIFY, PARTIAL_CLOSE
    asset               VARCHAR(20) NOT NULL,
    direction           VARCHAR(20) NOT NULL,
    entry_price_ref     DECIMAL(20, 8),
    stop_loss           DECIMAL(20, 8),
    take_profit_1       DECIMAL(20, 8),
    take_profit_2       DECIMAL(20, 8),
    lot_size            DECIMAL(10, 4),
    risk_percent        DECIMAL(6, 4),
    risk_dollars        DECIMAL(12, 2),
    risk_reward_ratio   DECIMAL(6, 2),
    signal_score        DECIMAL(4, 2),
    regime              VARCHAR(30),
    regime_confidence   DECIMAL(4, 2),
    mtf_alignment_score DECIMAL(4, 2),
    mtf_alignment_quality VARCHAR(10),
    volatility_state    VARCHAR(20),
    atr_current         DECIMAL(20, 8),
    atr_percentile      DECIMAL(5, 1),
    adx_value           DECIMAL(6, 2),
    strategy_id         VARCHAR(50),
    operational_mode    VARCHAR(20),
    status              VARCHAR(30) NOT NULL DEFAULT 'GENERATED',
    -- Status: GENERATED, PUBLISHED, ACKNOWLEDGED, FILLED, REJECTED, FILTERED, EXPIRED
    rejection_reason    VARCHAR(100),
    generation_latency_ms INTEGER,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    published_at        TIMESTAMPTZ,
    acknowledged_at     TIMESTAMPTZ,
    executed_at         TIMESTAMPTZ,
    metadata            JSONB
);

CREATE INDEX idx_signals_asset ON signals(asset);
CREATE INDEX idx_signals_created ON signals(created_at);
CREATE INDEX idx_signals_status ON signals(status);
CREATE INDEX idx_signals_regime ON signals(regime);


-- ============================================================================
-- 2. TRADES TABLE
-- Records every completed trade with full metrics.
-- ============================================================================
CREATE TABLE trades (
    id                      UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    trade_id                VARCHAR(100) UNIQUE NOT NULL,
    signal_id               VARCHAR(100) REFERENCES signals(signal_id),
    asset                   VARCHAR(20) NOT NULL,
    direction               VARCHAR(10) NOT NULL,
    entry_time              TIMESTAMPTZ NOT NULL,
    exit_time               TIMESTAMPTZ,
    hold_duration_minutes   INTEGER,
    entry_price             DECIMAL(20, 8) NOT NULL,
    exit_price              DECIMAL(20, 8),
    stop_loss               DECIMAL(20, 8) NOT NULL,
    take_profit             DECIMAL(20, 8),
    lot_size                DECIMAL(10, 4) NOT NULL,
    risk_percent            DECIMAL(6, 4) NOT NULL,
    risk_dollars            DECIMAL(12, 2) NOT NULL,

    -- P&L
    pnl_dollars             DECIMAL(12, 2),
    pnl_percent             DECIMAL(8, 4),
    pnl_pips                DECIMAL(10, 2),
    actual_rr               DECIMAL(6, 2),
    planned_rr              DECIMAL(6, 2),

    -- Excursion analysis
    max_favorable_excursion DECIMAL(20, 8),   -- Highest profit during trade
    max_adverse_excursion   DECIMAL(20, 8),   -- Worst drawdown during trade
    mfe_price               DECIMAL(20, 8),
    mae_price               DECIMAL(20, 8),

    -- Execution quality
    slippage_entry_points   DECIMAL(10, 2),
    slippage_exit_points    DECIMAL(10, 2),
    spread_at_entry         DECIMAL(10, 2),
    spread_at_exit          DECIMAL(10, 2),
    commission              DECIMAL(10, 4),
    swap                    DECIMAL(10, 4),

    -- Context
    regime_at_entry         VARCHAR(30),
    regime_at_exit          VARCHAR(30),
    signal_score            DECIMAL(4, 2),
    mtf_alignment_score     DECIMAL(4, 2),
    exit_reason             VARCHAR(50),
    -- EXIT_REASONS: TP1_HIT, TP2_HIT, SL_HIT, TRAILING_STOP, SIGNAL_EXIT,
    --              REGIME_SHIFT, EMERGENCY, MANUAL, BREAKEVEN_STOP

    strategy_id             VARCHAR(50),
    magic_number            INTEGER,
    mt5_ticket              BIGINT,
    notes                   TEXT,
    metadata                JSONB,

    -- Status
    status                  VARCHAR(20) NOT NULL DEFAULT 'OPEN',
    -- OPEN, CLOSED, PARTIALLY_CLOSED
    created_at              TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at              TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_trades_asset ON trades(asset);
CREATE INDEX idx_trades_entry_time ON trades(entry_time);
CREATE INDEX idx_trades_exit_time ON trades(exit_time);
CREATE INDEX idx_trades_status ON trades(status);
CREATE INDEX idx_trades_regime ON trades(regime_at_entry);
CREATE INDEX idx_trades_direction ON trades(direction);


-- ============================================================================
-- 3. PARTIAL CLOSES TABLE
-- Records each partial close event for a trade.
-- ============================================================================
CREATE TABLE partial_closes (
    id                  UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    trade_id            VARCHAR(100) REFERENCES trades(trade_id),
    close_time          TIMESTAMPTZ NOT NULL,
    close_price         DECIMAL(20, 8) NOT NULL,
    close_volume        DECIMAL(10, 4) NOT NULL,
    remaining_volume    DECIMAL(10, 4) NOT NULL,
    pnl_dollars         DECIMAL(12, 2),
    reason              VARCHAR(50),  -- TP1_HIT, TP2_HIT, SIGNAL
    created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_partial_trade ON partial_closes(trade_id);


-- ============================================================================
-- 4. DAILY SUMMARIES TABLE
-- ============================================================================
CREATE TABLE daily_summaries (
    id                      UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    date                    DATE UNIQUE NOT NULL,
    starting_equity         DECIMAL(14, 2) NOT NULL,
    ending_equity           DECIMAL(14, 2) NOT NULL,
    high_watermark          DECIMAL(14, 2),
    low_watermark           DECIMAL(14, 2),
    daily_pnl_dollars       DECIMAL(12, 2),
    daily_pnl_percent       DECIMAL(8, 4),
    max_drawdown_intraday   DECIMAL(8, 4),
    total_trades            INTEGER DEFAULT 0,
    winning_trades          INTEGER DEFAULT 0,
    losing_trades           INTEGER DEFAULT 0,
    win_rate                DECIMAL(6, 4),
    profit_factor           DECIMAL(8, 4),
    average_win             DECIMAL(12, 2),
    average_loss            DECIMAL(12, 2),
    average_rr_achieved     DECIMAL(6, 2),
    largest_win             DECIMAL(12, 2),
    largest_loss            DECIMAL(12, 2),
    total_commission        DECIMAL(10, 4),
    total_swap              DECIMAL(10, 4),
    total_slippage_cost     DECIMAL(10, 4),
    signals_generated       INTEGER DEFAULT 0,
    signals_filtered        INTEGER DEFAULT 0,
    signals_executed        INTEGER DEFAULT 0,
    signals_rejected_ea     INTEGER DEFAULT 0,
    trades_by_asset         JSONB,
    pnl_by_asset            JSONB,
    trades_by_regime        JSONB,
    pnl_by_regime           JSONB,
    allocation_weights      JSONB,
    mode_time_hours         JSONB,   -- {"NORMAL": 20, "REDUCED": 4}
    kill_switch_activations INTEGER DEFAULT 0,
    self_improvement_actions JSONB,
    created_at              TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_daily_date ON daily_summaries(date);


-- ============================================================================
-- 5. MONTHLY SUMMARIES TABLE
-- ============================================================================
CREATE TABLE monthly_summaries (
    id                      UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    month                   VARCHAR(7) UNIQUE NOT NULL,  -- "2026-03"
    starting_equity         DECIMAL(14, 2) NOT NULL,
    ending_equity           DECIMAL(14, 2) NOT NULL,
    monthly_pnl_dollars     DECIMAL(12, 2),
    monthly_pnl_percent     DECIMAL(8, 4),
    max_drawdown_monthly    DECIMAL(8, 4),
    total_trades            INTEGER DEFAULT 0,
    win_rate                DECIMAL(6, 4),
    profit_factor           DECIMAL(8, 4),
    sharpe_ratio            DECIMAL(6, 4),
    sortino_ratio           DECIMAL(6, 4),
    calmar_ratio            DECIMAL(6, 4),
    avg_daily_return        DECIMAL(8, 6),
    daily_return_std        DECIMAL(8, 6),
    best_day_pnl            DECIMAL(12, 2),
    worst_day_pnl           DECIMAL(12, 2),
    max_consecutive_wins    INTEGER,
    max_consecutive_losses  INTEGER,
    avg_hold_time_minutes   DECIMAL(10, 2),
    total_costs             DECIMAL(12, 2),
    net_pnl_after_costs     DECIMAL(12, 2),
    performance_by_asset    JSONB,
    performance_by_regime   JSONB,
    regime_distribution     JSONB,
    system_uptime_percent   DECIMAL(6, 2),
    created_at              TIMESTAMPTZ NOT NULL DEFAULT NOW()
);


-- ============================================================================
-- 6. RISK EVENTS TABLE
-- Logs every risk-related event: mode changes, kill-switch activations, etc.
-- ============================================================================
CREATE TABLE risk_events (
    id                  UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    event_type          VARCHAR(50) NOT NULL,
    -- EVENT_TYPES: MODE_CHANGE, KILL_SWITCH, DRAWDOWN_BREACH, CONSECUTIVE_LOSS,
    --             CORRELATION_ALERT, HEAT_LIMIT, POSITION_LOSS_LIMIT,
    --             HEARTBEAT_TIMEOUT, EQUITY_ANOMALY, SPREAD_ANOMALY,
    --             EMERGENCY_CLOSE_ALL
    severity            VARCHAR(10) NOT NULL,  -- INFO, WARNING, CRITICAL, EMERGENCY
    old_mode            VARCHAR(20),
    new_mode            VARCHAR(20),
    trigger_value       DECIMAL(10, 4),
    threshold_value     DECIMAL(10, 4),
    description         TEXT NOT NULL,
    account_equity      DECIMAL(14, 2),
    portfolio_heat      DECIMAL(6, 4),
    daily_drawdown      DECIMAL(8, 4),
    monthly_drawdown    DECIMAL(8, 4),
    open_positions      INTEGER,
    action_taken        TEXT,
    operator_notified   BOOLEAN DEFAULT FALSE,
    operator_acknowledged BOOLEAN DEFAULT FALSE,
    acknowledged_at     TIMESTAMPTZ,
    metadata            JSONB,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_risk_events_type ON risk_events(event_type);
CREATE INDEX idx_risk_events_severity ON risk_events(severity);
CREATE INDEX idx_risk_events_created ON risk_events(created_at);


-- ============================================================================
-- 7. REGIME HISTORY TABLE
-- Records regime classifications over time for each asset.
-- ============================================================================
CREATE TABLE regime_history (
    id                  UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    asset               VARCHAR(20) NOT NULL,
    regime              VARCHAR(30) NOT NULL,
    confidence          DECIMAL(4, 2),
    atr_current         DECIMAL(20, 8),
    atr_percentile      DECIMAL(5, 1),
    adx_value           DECIMAL(6, 2),
    bb_width_percentile DECIMAL(5, 1),
    vol_expanding       BOOLEAN,
    vol_spike           BOOLEAN,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_regime_asset ON regime_history(asset);
CREATE INDEX idx_regime_created ON regime_history(created_at);

-- TimescaleDB hypertable (if extension available)
-- SELECT create_hypertable('regime_history', 'created_at', if_not_exists => TRUE);


-- ============================================================================
-- 8. ALLOCATION HISTORY TABLE
-- Records asset allocation weight changes over time.
-- ============================================================================
CREATE TABLE allocation_history (
    id                  UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    btcusd_weight       DECIMAL(6, 4) NOT NULL,
    ethusd_weight       DECIMAL(6, 4) NOT NULL,
    xauusd_weight       DECIMAL(6, 4) NOT NULL,
    btcusd_performance  DECIMAL(6, 4),
    ethusd_performance  DECIMAL(6, 4),
    xauusd_performance  DECIMAL(6, 4),
    btc_eth_correlation DECIMAL(6, 4),
    gold_crypto_correlation DECIMAL(6, 4),
    change_reason       TEXT,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW()
);


-- ============================================================================
-- 9. SELF-IMPROVEMENT AUDIT LOG
-- Records every parameter change made by the self-improvement module.
-- ============================================================================
CREATE TABLE self_improvement_log (
    id                  UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    parameter_name      VARCHAR(100) NOT NULL,
    old_value           DECIMAL(20, 8),
    new_value           DECIMAL(20, 8),
    change_reason       TEXT NOT NULL,
    performance_metrics JSONB,      -- Metrics that triggered the change
    bounded             BOOLEAN DEFAULT FALSE,  -- Was the change limited by safety bounds?
    original_target     DECIMAL(20, 8),  -- What the algorithm wanted before bounding
    created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_self_improvement_param ON self_improvement_log(parameter_name);
CREATE INDEX idx_self_improvement_created ON self_improvement_log(created_at);


-- ============================================================================
-- 10. SYSTEM HEALTH TABLE
-- Records system health metrics at regular intervals.
-- ============================================================================
CREATE TABLE system_health (
    id                      UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    openclaw_uptime_sec     INTEGER,
    ea_uptime_sec           INTEGER,
    cpu_usage_percent       DECIMAL(5, 2),
    memory_usage_mb         DECIMAL(10, 2),
    disk_usage_percent      DECIMAL(5, 2),
    data_feed_latency_ms    INTEGER,
    ipc_latency_ms          INTEGER,
    db_write_latency_ms     INTEGER,
    heartbeat_roundtrip_ms  INTEGER,
    operational_mode        VARCHAR(20),
    data_feed_status        VARCHAR(10),  -- OK, STALE, DOWN
    database_status         VARCHAR(10),
    ea_status               VARCHAR(10),
    account_equity          DECIMAL(14, 2),
    account_balance         DECIMAL(14, 2),
    margin_level            DECIMAL(10, 2),
    open_positions          INTEGER,
    portfolio_heat          DECIMAL(6, 4),
    created_at              TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_health_created ON system_health(created_at);

-- TimescaleDB hypertable for efficient time-series storage
-- SELECT create_hypertable('system_health', 'created_at', if_not_exists => TRUE);


-- ============================================================================
-- 11. EQUITY SNAPSHOTS TABLE
-- Records equity at regular intervals for curve plotting.
-- ============================================================================
CREATE TABLE equity_snapshots (
    id              UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    equity          DECIMAL(14, 2) NOT NULL,
    balance         DECIMAL(14, 2) NOT NULL,
    unrealized_pnl  DECIMAL(12, 2),
    margin_used     DECIMAL(12, 2),
    daily_pnl       DECIMAL(12, 2),
    monthly_pnl     DECIMAL(12, 2),
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_equity_created ON equity_snapshots(created_at);

-- TimescaleDB
-- SELECT create_hypertable('equity_snapshots', 'created_at', if_not_exists => TRUE);


-- ============================================================================
-- 12. CORRELATION HISTORY
-- ============================================================================
CREATE TABLE correlation_history (
    id                      UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    btc_eth_correlation     DECIMAL(6, 4),
    btc_gold_correlation    DECIMAL(6, 4),
    eth_gold_correlation    DECIMAL(6, 4),
    crypto_gold_composite   DECIMAL(6, 4),  -- Combined crypto vs gold
    lookback_days           INTEGER NOT NULL DEFAULT 30,
    created_at              TIMESTAMPTZ NOT NULL DEFAULT NOW()
);


-- ============================================================================
-- 13. BACKTEST RESULTS TABLE
-- ============================================================================
CREATE TABLE backtest_results (
    id                      UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    backtest_name           VARCHAR(200) NOT NULL,
    start_date              DATE NOT NULL,
    end_date                DATE NOT NULL,
    initial_equity          DECIMAL(14, 2),
    final_equity            DECIMAL(14, 2),
    total_return_pct        DECIMAL(10, 4),
    max_drawdown_pct        DECIMAL(8, 4),
    sharpe_ratio            DECIMAL(6, 4),
    sortino_ratio           DECIMAL(6, 4),
    profit_factor           DECIMAL(8, 4),
    win_rate                DECIMAL(6, 4),
    total_trades            INTEGER,
    avg_trade_pnl           DECIMAL(12, 2),
    parameters              JSONB NOT NULL,
    strategy_version        VARCHAR(50),
    notes                   TEXT,
    created_at              TIMESTAMPTZ NOT NULL DEFAULT NOW()
);


-- ============================================================================
-- DATA RETENTION POLICIES
-- ============================================================================

-- Keep detailed data for 1 year, then archive
-- system_health: keep 90 days detailed, archive older
-- equity_snapshots: keep 1 year detailed (1-minute), then downsample to hourly
-- regime_history: keep 6 months detailed, archive older

-- Example retention policy (TimescaleDB):
-- SELECT add_retention_policy('system_health', INTERVAL '90 days');
-- SELECT add_retention_policy('equity_snapshots', INTERVAL '365 days');
-- SELECT add_retention_policy('regime_history', INTERVAL '180 days');


-- ============================================================================
-- MATERIALIZED VIEWS FOR PERFORMANCE DASHBOARDS
-- ============================================================================

-- Hourly equity summary
CREATE MATERIALIZED VIEW IF NOT EXISTS equity_hourly AS
SELECT
    date_trunc('hour', created_at) AS hour,
    AVG(equity) AS avg_equity,
    MAX(equity) AS max_equity,
    MIN(equity) AS min_equity,
    (array_agg(equity ORDER BY created_at DESC))[1] AS close_equity
FROM equity_snapshots
GROUP BY date_trunc('hour', created_at)
ORDER BY hour;

-- Trade performance by asset (last 30 days)
CREATE MATERIALIZED VIEW IF NOT EXISTS asset_performance_30d AS
SELECT
    asset,
    COUNT(*) AS total_trades,
    SUM(CASE WHEN pnl_dollars > 0 THEN 1 ELSE 0 END) AS wins,
    SUM(CASE WHEN pnl_dollars <= 0 THEN 1 ELSE 0 END) AS losses,
    ROUND(SUM(CASE WHEN pnl_dollars > 0 THEN 1.0 ELSE 0 END) / NULLIF(COUNT(*), 0), 4) AS win_rate,
    SUM(pnl_dollars) AS total_pnl,
    AVG(pnl_dollars) AS avg_pnl,
    AVG(actual_rr) AS avg_rr,
    MAX(pnl_dollars) AS best_trade,
    MIN(pnl_dollars) AS worst_trade
FROM trades
WHERE exit_time >= NOW() - INTERVAL '30 days'
  AND status = 'CLOSED'
GROUP BY asset;

-- Trade performance by regime (last 30 days)
CREATE MATERIALIZED VIEW IF NOT EXISTS regime_performance_30d AS
SELECT
    regime_at_entry,
    COUNT(*) AS total_trades,
    ROUND(SUM(CASE WHEN pnl_dollars > 0 THEN 1.0 ELSE 0 END) / NULLIF(COUNT(*), 0), 4) AS win_rate,
    SUM(pnl_dollars) AS total_pnl,
    AVG(actual_rr) AS avg_rr
FROM trades
WHERE exit_time >= NOW() - INTERVAL '30 days'
  AND status = 'CLOSED'
GROUP BY regime_at_entry;


-- ============================================================================
-- UTILITY FUNCTIONS
-- ============================================================================

-- Function to refresh all materialized views
CREATE OR REPLACE FUNCTION refresh_dashboard_views()
RETURNS void AS $$
BEGIN
    REFRESH MATERIALIZED VIEW equity_hourly;
    REFRESH MATERIALIZED VIEW asset_performance_30d;
    REFRESH MATERIALIZED VIEW regime_performance_30d;
END;
$$ LANGUAGE plpgsql;
